version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "5683:5683/udp"
    depends_on:
      - postgres
    environment:
      POSTGRESQL_DB_URL: "${POSTGRESQL_DB_USER}:${POSTGRESQL_DB_PASS}@postgres"
      MYSQL_DB_URL: ${MYSQL_DB_URL}
      ALLOWED_BOT_USERS: ${ALLOWED_BOT_USERS}
      BOT_TOKEN: ${BOT_TOKEN}
      STATION_TYPE: ${STATION_TYPE}
      LOCATION_ID: ${LOCATION_ID}
      ENV: PROD

  postgres:
    image: postgres:14.2
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: ${POSTGRESQL_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_DB_PASS}
      POSTGRES_DB: sensordata
    volumes:
      - "/var/lib/postgresql/data"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - "8080:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana"

  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=sensordata

    profiles: [dev]

volumes:
  grafana_storage: {}
  mysql: {}
