{
 "title": "AIQ Data Dashboard",
 "time": { "from": "2024-10-07T13:28:29.000Z", "to": "2024-10-07T15:46:28.000Z" },
 "templating": {
  "list": [
   { "name": "border_router_id", "label": "Border Router Id", "query": "select id from border_routers" },
   { "name": "station_id", "label": "Sensor Station id", "query": "select id from stations" }
  ]
 },
 "panels": [
  {
   "title": "SCD41 Temperature in C",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", temperature FROM station_data inner join scd41_data on station_data.scd41_data_id=scd41_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "SVM41 Temperature in C",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", temperature FROM station_data inner join svm41_data on station_data.svm41_data_id=svm41_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "SCD41 CO2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", co2 FROM station_data inner join scd41_data on station_data.scd41_data_id=scd41_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "SCD41 Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", humidity FROM station_data inner join scd41_data on station_data.scd41_data_id=scd41_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "SVM41 Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", humidity FROM station_data inner join svm41_data on station_data.svm41_data_id=svm41_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "SVM41 NOX Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", nox_index FROM station_data inner join svm41_data on station_data.svm41_data_id=svm41_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "SVM41 VOC Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", voc_index FROM station_data inner join svm41_data on station_data.svm41_data_id=svm41_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "EN160 ECO2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", eco2 FROM station_data inner join ens160_data on station_data.ens160_data_id=ens160_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "ENS160 VOC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", tvoc FROM station_data inner join ens160_data on station_data.ens160_data_id=ens160_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "ENS 160 Air Quality Index",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", aqi FROM station_data inner join ens160_data on station_data.ens160_data_id=ens160_data.id WHERE station_id = $station_id AND border_router_id = $border_router_id ORDER BY \"timestamp\" "
    }
   ]
  }
 ]
}