"""Improve DB schema with new sensor data tables

Revision ID: 3953e2822334
Revises: b901ade8852b
Create Date: 2024-08-29 16:05:39.488860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3953e2822334"
down_revision: Union[str, None] = "b901ade8852b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ens160_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("eco2", sa.Integer(), nullable=False),
        sa.Column("tvoc", sa.Integer(), nullable=False),
        sa.Column("aqi", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_ens160_data"),
    )
    op.create_table(
        "scd41_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("co2", sa.VARCHAR(length=20), nullable=False),
        sa.Column("temperature", sa.VARCHAR(length=20), nullable=False),
        sa.Column("humidity", sa.VARCHAR(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_scd41_data"),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_stations"),
    )
    op.create_table(
        "svm41_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("temperature", sa.VARCHAR(length=20), nullable=False),
        sa.Column("humidity", sa.VARCHAR(length=20), nullable=False),
        sa.Column("nox_index", sa.VARCHAR(length=20), nullable=False),
        sa.Column("voc_index", sa.VARCHAR(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_esvm41_data"),
    )
    op.create_table(
        "station_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("scd41_data_id", sa.INTEGER(), nullable=True),
        sa.Column("ens160_data_id", sa.INTEGER(), nullable=True),
        sa.Column("svm41_data_id", sa.INTEGER(), nullable=True),
        sa.Column("station_id", sa.INTEGER(), nullable=False),
        sa.Column("border_router_id", sa.INTEGER(), nullable=True),
        sa.Column("timestamp", sa.VARCHAR(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["border_router_id"],
            ["border_routers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ens160_data_id"],
            ["ens160_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scd41_data_id"],
            ["scd41_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["svm41_data_id"],
            ["svm41_data.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="pk_sensor_data"),
    )
    op.drop_table("sensor_data")
    op.add_column("border_routers", sa.Column("location", sa.VARCHAR(length=36), nullable=False))
    op.drop_column("border_routers", "location_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("border_routers", sa.Column("location_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_column("border_routers", "location")
    op.create_table(
        "sensor_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("co2", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("temperature", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("humidity", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("eco2", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tvoc", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("aqi", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sensor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("timestamp", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("location_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_sensor_data"),
    )
    op.drop_table("station_data")
    op.drop_table("svm41_data")
    op.drop_table("stations")
    op.drop_table("scd41_data")
    op.drop_table("ens160_data")
    # ### end Alembic commands ###
