"""Add support for bme688

Revision ID: 74b685228bd5
Revises: 3953e2822334
Create Date: 2024-12-13 17:16:27.391847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b685228bd5'
down_revision: Union[str, None] = '3953e2822334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bme688_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.VARCHAR(length=20), nullable=False),
    sa.Column('humidity', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pressure', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gas_resistance', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_bme688_data')
    )
    op.add_column('station_data', sa.Column('bme688_data_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'station_data', 'bme688_data', ['bme688_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station_data', type_='foreignkey')
    op.drop_column('station_data', 'bme688_data_id')
    op.drop_table('bme688_data')
    # ### end Alembic commands ###
