"""Add indexes to important columns

Revision ID: 8d2149a11367
Revises: 74b685228bd5
Create Date: 2025-01-20 17:31:16.781760

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d2149a11367"
down_revision: Union[str, None] = "74b685228bd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.create_index(
            op.f("ix_station_data_border_router_id"), "station_data", ["border_router_id"], unique=False, postgresql_concurrently=True
        )
        op.create_index(op.f("ix_station_data_station_id"), "station_data", ["station_id"], unique=False, postgresql_concurrently=True)
        op.create_index(op.f("ix_station_data_timestamp"), "station_data", ["timestamp"], unique=False, postgresql_concurrently=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_station_data_timestamp"), table_name="station_data")
    op.drop_index(op.f("ix_station_data_station_id"), table_name="station_data")
    op.drop_index(op.f("ix_station_data_border_router_id"), table_name="station_data")
    # ### end Alembic commands ###
