"""Added border routers table

Revision ID: b901ade8852b
Revises: 65856ee0df0e
Create Date: 2024-02-27 15:30:05.947051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b901ade8852b'
down_revision: Union[str, None] = '65856ee0df0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('border_routers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ipv4_address', sa.VARCHAR(length=25), nullable=False),
    sa.Column('location_id', sa.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_border_routers')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('border_routers')
    # ### end Alembic commands ###
